
/*
 * This file will be processed by the preprocessor
 * and the output file _autogenerated.ld (see pre-build steps)
 * is included inside the linker script
 *
 * In this way we can share constants between
 * the C program and the linker file
*/

#include "App/Inc/addresses.h"

#ifdef LINKER_SCRIPT
_BOOT_ADDRESS = BOOT_ADDRESS;
#endif
